# Generated by Django 3.0.3 on 2020-03-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcreation',
            name='status1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketcreation',
            name='status2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
